# Generated by Django 5.2.5 on 2025-08-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baixo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='LOW'),
        ),
    ]
