# Generated by Django 5.2.5 on 2025-08-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_participants_delete_projectinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('canceled', 'Cancelado'), ('pendent', 'Pendente')], default='in_progress', max_length=20),
        ),
    ]
