# Generated by Django 5.2.4 on 2025-08-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_senha_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(default=models.EmailField(max_length=254, unique=True), max_length=255, unique=True),
        ),
    ]
